export const nationalities = [
    "Afghan", "Albanian", "Algerian", "American", "Andorran", "Angolan",
    "Antiguan", "Argentine", "Armenian", "Australian", "Austrian", "Azerbaijani",
    "Bahamian", "Bahraini", "Bangladeshi", "Barbadian", "Belarusian", "Belgian",
    "Belizean", "Beninese", "Bhutanese", "Bolivian", "Bosnian", "Botswanan",
    "Brazilian", "British", "Bruneian", "Bulgarian", "Burkinabe", "Burmese",
    "Burundian", "Cambodian", "Cameroonian", "Canadian", "Cape Verdean",
    "Central African", "Chadian", "Chilean", "Chinese", "Colombian",
    "Comoran", "Congolese", "Costa Rican", "Croatian", "Cuban", "Cypriot",
    "Czech", "Danish", "Djiboutian", "Dominican", "Dutch", "East Timorese",
    "Ecuadorean", "Egyptian", "Emirati", "Equatorial Guinean", "Eritrean",
    "Estonian", "Ethiopian", "Fijian", "Finnish", "French", "Gabonese",
    "Gambian", "Georgian", "German", "Ghanaian", "Greek", "Grenadian",
    "Guatemalan", "Guinean", "Guinea-Bissauan", "Guyanese", "Haitian",
    "Honduran", "Hungarian", "Icelander", "Indian", "Indonesian", "Iranian",
    "Iraqi", "Irish", "Italian", "Ivorian", "Jamaican", "Japanese",
    "Jordanian", "Kazakh", "Kenyan", "Kittian and Nevisian", "Kuwaiti",
    "Kyrgyz", "Laotian", "Latvian", "Lebanese", "Liberian", "Libyan",
    "Liechtensteiner", "Lithuanian", "Luxembourger", "Macedonian", "Malagasy",
    "Malawian", "Malaysian", "Maldivian", "Malian", "Maltese", "Marshallese",
    "Mauritanian", "Mauritian", "Mexican", "Micronesian", "Moldovan",
    "Monacan", "Mongolian", "Montenegrin", "Moroccan", "Mozambican",
    "Namibian", "Nauruan", "Nepalese", "New Zealander", "Nicaraguan",
    "Nigerien", "Nigerian", "Norwegian", "Omani", "Pakistani", "Palestine", "Palauan",
    "Panamanian", "Papua New Guinean", "Paraguayan", "Peruvian", "Philippine",
    "Polish", "Portuguese", "Qatari", "Romanian", "Russian", "Rwandan",
    "Saint Lucian", "Salvadoran", "Samoan", "San Marinese", "Sao Tomean",
    "Saudi", "Senegalese", "Serbian", "Seychellois", "Sierra Leonean",
    "Singaporean", "Slovak", "Slovenian", "Solomon Islander", "Somali",
    "South African", "South Korean", "South Sudanese", "Spanish", "Sri Lankan",
    "Sudanese", "Surinamer", "Swazi", "Swedish", "Swiss", "Syrian",
    "Taiwanese", "Tajik", "Tanzanian", "Thai", "Togolese", "Tongan",
    "Trinidadian or Tobagonian", "Tunisian", "Turkish", "Turkmen",
    "Tuvaluan", "Ugandan", "Ukrainian", "Uruguayan", "Uzbek", "Vanuatuan",
    "Venezuelan", "Vietnamese", "Yemeni", "Zambian", "Zimbabwean"
];


export const locationIssues = [
    "Location Issue","Room", "Bathroom", "Hangout Room", "TV Room", "Laundry Area", "Pest",
]


export const roomMaintenanceIssues = [
    "Room Maintenance Issues",
    "Socket some equipment stuck",
    "Socket some sparks",
    "Socket some no electricity",
    "Socket some burned",
    "Room light furniture area flickering",
    "Room light furniture area not working at all",
    "Room light beds area flickering",
    "Room light beds area not working at all",
    "General washroom light not working",
    "General washroom light flickering",
    "Toilet light not working at all",
    "Toilet light flickering",
    "Fan beds area slow",
    "Fan beds area not working at all",
    "Fan furniture area slow",
    "Fan furniture area not working at all",
    "Ventilation issue",
    "Air conditioner water leakage",
    "Washroom water tap shower broken",
    "Sink water tap loose",
    "Toilet water tap is loose",
    "Toilet water tap damage",
    "No water from water tap",
    "Toilet water storage leakage",
    "Sink clogged",
    "Washroom drain clogged",
    "Toilet flush not working",
    "Water dispenser water slow",
    "Sink water tap broken",
    "Sink pipe leakage",
    "Toilet door lock broken",
    "Door knob stuck/jammed",
    "Toilet door damage/broken/hole",
    "Washroom door lock broken",
    "Washroom door damage/broken/hole",
    "Wardrobe key lock jammed",
    "Room key lost",
    "All room and wardrobe keys missing",
    "Bed frame broken",
    "Wardrobe keys both sides not working",
    "Wardrobe key lock jammed",
    "Sofa damaged",
    "Fridge 06 not working",
    "Fridge freezer problem",
    "Fridge chiller problem",
    "Water cooler not working properly",
    "Ceiling is leaking",
    "Roof/ceiling leaking",
    "Wall water leaking",
    "Toilet drain hole no cover",
    "Washroom drain hole no cover",
    "Pest infestation reported",
    "Cockroach issue",
    "Mosquito issue",
    "Rat infestation"
];
