export const nationalities = [
    "Afghan", "Albanian", "Algerian", "American", "Andorran", "Angolan",
    "Antiguan", "Argentine", "Armenian", "Australian", "Austrian", "Azerbaijani",
    "Bahamian", "Bahraini", "Bangladeshi", "Barbadian", "Belarusian", "Belgian",
    "Belizean", "Beninese", "Bhutanese", "Bolivian", "Bosnian", "Botswanan",
    "Brazilian", "British", "Bruneian", "Bulgarian", "Burkinabe", "Burmese",
    "Burundian", "Cambodian", "Cameroonian", "Canadian", "Cape Verdean",
    "Central African", "Chadian", "Chilean", "Chinese", "Colombian",
    "Comoran", "Congolese", "Costa Rican", "Croatian", "Cuban", "Cypriot",
    "Czech", "Danish", "Djiboutian", "Dominican", "Dutch", "East Timorese",
    "Ecuadorean", "Egyptian", "Emirati", "Equatorial Guinean", "Eritrean",
    "Estonian", "Ethiopian", "Fijian", "Finnish", "French", "Gabonese",
    "Gambian", "Georgian", "German", "Ghanaian", "Greek", "Grenadian",
    "Guatemalan", "Guinean", "Guinea-Bissauan", "Guyanese", "Haitian",
    "Honduran", "Hungarian", "Icelander", "Indian", "Indonesian", "Iranian",
    "Iraqi", "Irish", "Italian", "Ivorian", "Jamaican", "Japanese",
    "Jordanian", "Kazakh", "Kenyan", "Kittian and Nevisian", "Kuwaiti",
    "Kyrgyz", "Laotian", "Latvian", "Lebanese", "Liberian", "Libyan",
    "Liechtensteiner", "Lithuanian", "Luxembourger", "Macedonian", "Malagasy",
    "Malawian", "Malaysian", "Maldivian", "Malian", "Maltese", "Marshallese",
    "Mauritanian", "Mauritian", "Mexican", "Micronesian", "Moldovan",
    "Monacan", "Mongolian", "Montenegrin", "Moroccan", "Mozambican",
    "Namibian", "Nauruan", "Nepalese", "New Zealander", "Nicaraguan",
    "Nigerien", "Nigerian", "Norwegian", "Omani", "Pakistani", "Palestine", "Palauan",
    "Panamanian", "Papua New Guinean", "Paraguayan", "Peruvian", "Philippine",
    "Polish", "Portuguese", "Qatari", "Romanian", "Russian", "Rwandan",
    "Saint Lucian", "Salvadoran", "Samoan", "San Marinese", "Sao Tomean",
    "Saudi", "Senegalese", "Serbian", "Seychellois", "Sierra Leonean",
    "Singaporean", "Slovak", "Slovenian", "Solomon Islander", "Somali",
    "South African", "South Korean", "South Sudanese", "Spanish", "Sri Lankan",
    "Sudanese", "Surinamer", "Swazi", "Swedish", "Swiss", "Syrian",
    "Taiwanese", "Tajik", "Tanzanian", "Thai", "Togolese", "Tongan",
    "Trinidadian or Tobagonian", "Tunisian", "Turkish", "Turkmen",
    "Tuvaluan", "Ugandan", "Ukrainian", "Uruguayan", "Uzbek", "Vanuatuan",
    "Venezuelan", "Vietnamese", "Yemeni", "Zambian", "Zimbabwean"
];

export const religions = [
    "Christianity", "Islam", "Judaism", "Baha'i Faith", "Hinduism", "Buddhism", "Jainism", "Sikhism",
    "Taoism (Daoism)", "Confucianism", "Shinto", "Yoruba Religion", "Vodou", "Santería", "Native American Spirituality",
    "Aboriginal Spirituality", "Maori Religion", "Zoroastrianism", "Atheism", "Agnosticism", "Spirituality"
]

export const maleBlockOptions = ["Block 25H", "Block 25I", "Block 25A", "Block 25D", "Block 25E"];
export const femaleBlockOptions = ["Block 18A", "Block 18B", "Block 18C", "Block 18D"];

export const roomMaintenanceIssues = [
    "Room Maintenance Issues",
    "Socket some equipment stuck",
    "Socket some sparks",
    "Socket some no electricity",
    "Socket some burned",
    "Room light furniture area flickering",
    "Room light furniture area not working at all",
    "Room light beds area flickering",
    "Room light beds area not working at all",
    "General washroom light not working",
    "General washroom light flickering",
    "Toilet light not working at all",
    "Toilet light flickering",
    "Fan beds area slow",
    "Fan beds area not working at all",
    "Fan furniture area slow",
    "Fan furniture area not working at all",
    "Ventilation issue",
    "Air conditioner water leakage",
    "Washroom water tap shower broken",
    "Sink water tap loose",
    "Toilet water tap is loose",
    "Toilet water tap damage",
    "No water from water tap",
    "Toilet water storage leakage",
    "Sink clogged",
    "Washroom drain clogged",
    "Toilet flush not working",
    "Water dispenser water slow",
    "Sink water tap broken",
    "Sink pipe leakage",
    "Toilet door lock broken",
    "Door knob stuck/jammed",
    "Toilet door damage/broken/hole",
    "Washroom door lock broken",
    "Washroom door damage/broken/hole",
    "Wardrobe key lock jammed",
    "Room key lost",
    "All room and wardrobe keys missing",
    "Bed frame broken",
    "Wardrobe keys both sides not working",
    "Wardrobe key lock jammed",
    "Sofa damaged",
    "Fridge 06 not working",
    "Fridge freezer problem",
    "Fridge chiller problem",
    "Water cooler not working properly",
    "Ceiling is leaking",
    "Roof/ceiling leaking",
    "Wall water leaking",
    "Toilet drain hole no cover",
    "Washroom drain hole no cover",
    "Pest infestation reported",
    "Cockroach issue",
    "Mosquito issue",
    "Rat infestation"
];

export const blockData = {

    // this is 3 zone
    "Block 25H": {
        levelOne: {
            "01": ["Zone A", "Zone B", "Zone C"],
            "02": ["Zone A", "Zone B", "Zone C"],
            "03": ["Zone A", "Zone B", "Zone C"],
            "04": ["Zone A", "Zone B", "Zone C"],
            "05": ["Zone A", "Zone B", "Zone C"],
            "06": ["Zone A", "Zone B", "Zone C"],
            "07": ["Zone A", "Zone B", "Zone C"],
            "08": ["Zone A", "Zone B", "Zone C"],
            "09": ["Zone A", "Zone B", "Zone C"],
        },
        levelTwo: {
            "01": ["Zone A", "Zone B", "Zone C"],
            "02": ["Zone A", "Zone B", "Zone C"],
            "03": ["Zone A", "Zone B", "Zone C"],
            "04": ["Zone A", "Zone B", "Zone C"],
            "05": ["Zone A", "Zone B", "Zone C"],
            "06": ["Zone A", "Zone B", "Zone C"],
            "07": ["Zone A", "Zone B", "Zone C"],
            "08": ["Zone A", "Zone B", "Zone C"],
            "09": ["Zone A", "Zone B", "Zone C"],
            "10": ["Zone A", "Zone B", "Zone C"],
            "11": ["Zone A", "Zone B", "Zone C"],
            "12": ["Zone A", "Zone B", "Zone C"],
            "13": ["Zone A", "Zone B", "Zone C"],
            "14": ["Zone A", "Zone B", "Zone C"],
        },
        levelThree: {
            "01": ["Zone A", "Zone B", "Zone C"],
            "02": ["Zone A", "Zone B", "Zone C"],
            "03": ["Zone A", "Zone B", "Zone C"],
            "04": ["Zone A", "Zone B", "Zone C"],
            "05": ["Zone A", "Zone B", "Zone C"],
            "06": ["Zone A", "Zone B", "Zone C"],
            "07": ["Zone A", "Zone B", "Zone C"],
            "08": ["Zone A", "Zone B", "Zone C"],
            "09": ["Zone A", "Zone B", "Zone C"],
            "10": ["Zone A", "Zone B", "Zone C"],
            "11": ["Zone A", "Zone B", "Zone C"],
            "12": ["Zone A", "Zone B", "Zone C"],
            "13": ["Zone A", "Zone B", "Zone C"],
            "14": ["Zone A", "Zone B", "Zone C"],
        },
        levelFour: {
            "01": ["Zone A", "Zone B", "Zone C"],
            "02": ["Zone A", "Zone B", "Zone C"],
            "03": ["Zone A", "Zone B", "Zone C"],
            "04": ["Zone A", "Zone B", "Zone C"],
            "05": ["Zone A", "Zone B", "Zone C"],
            "06": ["Zone A", "Zone B", "Zone C"],
            "07": ["Zone A", "Zone B", "Zone C"],
            "08": ["Zone A", "Zone B", "Zone C"],
            "09": ["Zone A", "Zone B", "Zone C"],
            "10": ["Zone A", "Zone B", "Zone C"],
            "11": ["Zone A", "Zone B", "Zone C"],
            "12": ["Zone A", "Zone B", "Zone C"],
            "13": ["Zone A", "Zone B", "Zone C"],
            "14": ["Zone A", "Zone B", "Zone C"],
        },
    },

    // this is 2 zone
    "Block 25I": {
        levelOne: {
            "01": ["Zone A", "Zone B"],
            "02": ["Zone A", "Zone B"],
            "03": ["Zone A", "Zone B"],
            "04": ["Zone A", "Zone B"],
            "05": ["Zone A", "Zone B"],
            "06": ["Zone A", "Zone B"],
            "07": ["Zone A", "Zone B"],
            "08": ["Zone A", "Zone B"],
            "09": ["Zone A", "Zone B"],
            "10": ["Zone A", "Zone B"],
            "11": ["Zone A", "Zone B"],
            "12": ["Zone A", "Zone B"],
            "13": ["Zone A", "Zone B"],
        },
        levelTwo: {
            "01": ["Zone A", "Zone B"],
            "02": ["Zone A", "Zone B"],
            "03": ["Zone A", "Zone B"],
            "04": ["Zone A", "Zone B"],
            "05": ["Zone A", "Zone B"],
            "06": ["Zone A", "Zone B"],
            "07": ["Zone A", "Zone B"],
            "08": ["Zone A", "Zone B"],
            "09": ["Zone A", "Zone B"],
            "10": ["Zone A", "Zone B"],
            "11": ["Zone A", "Zone B"],
            "12": ["Zone A", "Zone B"],
            "13": ["Zone A", "Zone B"],
            "14": ["Zone A", "Zone B"],
            "15": ["Zone A", "Zone B"],
            "16": ["Zone A", "Zone B"],
            "17": ["Zone A", "Zone B"],
            "18": ["Zone A", "Zone B"],
            "19": ["Zone A", "Zone B"],
            "20": ["Zone A", "Zone B"],
            "21": ["Zone A", "Zone B"],
            "22": ["Zone A", "Zone B"],
            "23": ["Zone A", "Zone B"],
            "24": ["Zone A", "Zone B"],
            "25": ["Zone A", "Zone B"],
            "26": ["Zone A", "Zone B"],
            "27": ["Zone A", "Zone B"],
            "28": ["Zone A", "Zone B"],
            "29": ["Zone A", "Zone B"],
            "30": ["Zone A", "Zone B"]
        },
        levelThree: {
            "01": ["Zone A", "Zone B"],
            "02": ["Zone A", "Zone B"],
            "03": ["Zone A", "Zone B"],
            "04": ["Zone A", "Zone B"],
            "05": ["Zone A", "Zone B"],
            "06": ["Zone A", "Zone B"],
            "07": ["Zone A", "Zone B"],
            "08": ["Zone A", "Zone B"],
            "09": ["Zone A", "Zone B"],
            "10": ["Zone A", "Zone B"],
            "11": ["Zone A", "Zone B"],
            "12": ["Zone A", "Zone B"],
            "13": ["Zone A", "Zone B"],
            "14": ["Zone A", "Zone B"],
            "15": ["Zone A", "Zone B"],
            "16": ["Zone A", "Zone B"],
            "17": ["Zone A", "Zone B"],
            "18": ["Zone A", "Zone B"],
            "19": ["Zone A", "Zone B"],
            "20": ["Zone A", "Zone B"],
            "21": ["Zone A", "Zone B"],
            "22": ["Zone A", "Zone B"],
            "23": ["Zone A", "Zone B"],
            "24": ["Zone A", "Zone B"],
            "25": ["Zone A", "Zone B"],
            "26": ["Zone A", "Zone B"],
            "27": ["Zone A", "Zone B"],
            "28": ["Zone A", "Zone B"],
            "29": ["Zone A", "Zone B"],
            "30": ["Zone A", "Zone B"]
        },
        levelFour: {
            "01": ["Zone A", "Zone B"],
            "02": ["Zone A", "Zone B"],
            "03": ["Zone A", "Zone B"],
            "04": ["Zone A", "Zone B"],
            "05": ["Zone A", "Zone B"],
            "06": ["Zone A", "Zone B"],
            "07": ["Zone A", "Zone B"],
            "08": ["Zone A", "Zone B"],
            "09": ["Zone A", "Zone B"],
            "10": ["Zone A", "Zone B"],
            "11": ["Zone A", "Zone B"],
            "12": ["Zone A", "Zone B"],
            "13": ["Zone A", "Zone B"],
            "14": ["Zone A", "Zone B"],
            "15": ["Zone A", "Zone B"],
            "16": ["Zone A", "Zone B"],
            "17": ["Zone A", "Zone B"],
            "18": ["Zone A", "Zone B"],
            "19": ["Zone A", "Zone B"],
            "20": ["Zone A", "Zone B"],
            "21": ["Zone A", "Zone B"],
            "22": ["Zone A", "Zone B"],
            "23": ["Zone A", "Zone B"],
            "24": ["Zone A", "Zone B"],
            "25": ["Zone A", "Zone B"],
            "26": ["Zone A", "Zone B"],
            "27": ["Zone A", "Zone B"],
            "28": ["Zone A", "Zone B"],
            "29": ["Zone A", "Zone B"],
            "30": ["Zone A", "Zone B"]
        },
    },

    // this is 4 zone
    "Block 25A": {
        levelOne: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "11": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "12": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "13": ["Zone A", "Zone B", "Zone C", "Zone D"],
        },
        levelTwo: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "11": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "12": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "13": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "14": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "15": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "16": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "17": ["Zone A", "Zone B", "Zone C", "Zone D"]
        },
        levelThree: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "11": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "12": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "13": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "14": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "15": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "16": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "17": ["Zone A", "Zone B", "Zone C", "Zone D"]
        },
        levelFour: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "11": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "12": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "13": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "14": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "15": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "16": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "17": ["Zone A", "Zone B", "Zone C", "Zone D"]
        },
    },
    "Block 25D": {
        levelOne: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
        },
        levelTwo: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "11": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "12": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "13": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "14": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "15": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "16": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "17": ["Zone A", "Zone B", "Zone C", "Zone D"]
        },
        levelThree: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "11": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "12": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "13": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "14": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "15": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "16": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "17": ["Zone A", "Zone B", "Zone C", "Zone D"]
        },
        levelFour: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "11": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "12": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "13": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "14": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "15": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "16": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "17": ["Zone A", "Zone B", "Zone C", "Zone D"]
        },
    },
    "Block 25E": {
        levelOne: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
        },
        levelTwo: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "11": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "12": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "13": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "14": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "15": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "16": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "17": ["Zone A", "Zone B", "Zone C", "Zone D"]
        },
        levelThree: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "11": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "12": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "13": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "14": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "15": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "16": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "17": ["Zone A", "Zone B", "Zone C", "Zone D"]
        },
        levelFour: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "11": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "12": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "13": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "14": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "15": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "16": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "17": ["Zone A", "Zone B", "Zone C", "Zone D"]
        },
    },

    // this is 4 zone
    "Block 18A": {
        levelOne: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "11": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "12": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "13": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "14": ["Zone A", "Zone B", "Zone C", "Zone D"],
        },
        levelTwo: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "11": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "12": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "13": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "14": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "15": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "16": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "17": ["Zone A", "Zone B", "Zone C", "Zone D"]
        },
        levelThree: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "11": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "12": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "13": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "14": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "15": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "16": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "17": ["Zone A", "Zone B", "Zone C", "Zone D"]
        },
        levelFour: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "11": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "12": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "13": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "14": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "15": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "16": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "17": ["Zone A", "Zone B", "Zone C", "Zone D"]
        },
    },

    // this is 2 zone
    "Block 18B": {
        levelOne: {
            "01": ["Zone A", "Zone B"],
            "02": ["Zone A", "Zone B"],
            "03": ["Zone A", "Zone B"],
            "04": ["Zone A", "Zone B"],
            "05": ["Zone A", "Zone B"],
            "06": ["Zone A", "Zone B"],
            "07": ["Zone A", "Zone B"],
            "08": ["Zone A", "Zone B"],
            "09": ["Zone A", "Zone B"],
            "10": ["Zone A", "Zone B"],
            "11": ["Zone A", "Zone B"],
            "12": ["Zone A", "Zone B"],
            "13": ["Zone A", "Zone B"],
            "14": ["Zone A", "Zone B"],
            "15": ["Zone A", "Zone B"],
        },
        levelTwo: {
            "01": ["Zone A", "Zone B"],
            "02": ["Zone A", "Zone B"],
            "03": ["Zone A", "Zone B"],
            "04": ["Zone A", "Zone B"],
            "05": ["Zone A", "Zone B"],
            "06": ["Zone A", "Zone B"],
            "07": ["Zone A", "Zone B"],
            "08": ["Zone A", "Zone B"],
            "09": ["Zone A", "Zone B"],
            "10": ["Zone A", "Zone B"],
            "11": ["Zone A", "Zone B"],
            "12": ["Zone A", "Zone B"],
            "13": ["Zone A", "Zone B"],
            "14": ["Zone A", "Zone B"],
            "15": ["Zone A", "Zone B"],
            "16": ["Zone A", "Zone B"],
            "17": ["Zone A", "Zone B"],
            "18": ["Zone A", "Zone B"],
            "19": ["Zone A", "Zone B"],
            "20": ["Zone A", "Zone B"],
            "21": ["Zone A", "Zone B"],
            "22": ["Zone A", "Zone B"],
            "23": ["Zone A", "Zone B"],
            "24": ["Zone A", "Zone B"],
            "25": ["Zone A", "Zone B"],
            "26": ["Zone A", "Zone B"],
            "27": ["Zone A", "Zone B"],
            "28": ["Zone A", "Zone B"],
            "29": ["Zone A", "Zone B"],
            "30": ["Zone A", "Zone B"]
        },
        levelThree: {
            "01": ["Zone A", "Zone B"],
            "02": ["Zone A", "Zone B"],
            "03": ["Zone A", "Zone B"],
            "04": ["Zone A", "Zone B"],
            "05": ["Zone A", "Zone B"],
            "06": ["Zone A", "Zone B"],
            "07": ["Zone A", "Zone B"],
            "08": ["Zone A", "Zone B"],
            "09": ["Zone A", "Zone B"],
            "10": ["Zone A", "Zone B"],
            "11": ["Zone A", "Zone B"],
            "12": ["Zone A", "Zone B"],
            "13": ["Zone A", "Zone B"],
            "14": ["Zone A", "Zone B"],
            "15": ["Zone A", "Zone B"],
            "16": ["Zone A", "Zone B"],
            "17": ["Zone A", "Zone B"],
            "18": ["Zone A", "Zone B"],
            "19": ["Zone A", "Zone B"],
            "20": ["Zone A", "Zone B"],
            "21": ["Zone A", "Zone B"],
            "22": ["Zone A", "Zone B"],
            "23": ["Zone A", "Zone B"],
            "24": ["Zone A", "Zone B"],
            "25": ["Zone A", "Zone B"],
            "26": ["Zone A", "Zone B"],
            "27": ["Zone A", "Zone B"],
            "28": ["Zone A", "Zone B"],
            "29": ["Zone A", "Zone B"],
            "30": ["Zone A", "Zone B"]
        },
        levelFour: {
            "01": ["Zone A", "Zone B"],
            "02": ["Zone A", "Zone B"],
            "03": ["Zone A", "Zone B"],
            "04": ["Zone A", "Zone B"],
            "05": ["Zone A", "Zone B"],
            "06": ["Zone A", "Zone B"],
            "07": ["Zone A", "Zone B"],
            "08": ["Zone A", "Zone B"],
            "09": ["Zone A", "Zone B"],
            "10": ["Zone A", "Zone B"],
            "11": ["Zone A", "Zone B"],
            "12": ["Zone A", "Zone B"],
            "13": ["Zone A", "Zone B"],
            "14": ["Zone A", "Zone B"],
            "15": ["Zone A", "Zone B"],
            "16": ["Zone A", "Zone B"],
            "17": ["Zone A", "Zone B"],
            "18": ["Zone A", "Zone B"],
            "19": ["Zone A", "Zone B"],
            "20": ["Zone A", "Zone B"],
            "21": ["Zone A", "Zone B"],
            "22": ["Zone A", "Zone B"],
            "23": ["Zone A", "Zone B"],
            "24": ["Zone A", "Zone B"],
            "25": ["Zone A", "Zone B"],
            "26": ["Zone A", "Zone B"],
            "27": ["Zone A", "Zone B"],
            "28": ["Zone A", "Zone B"],
            "29": ["Zone A", "Zone B"],
            "30": ["Zone A", "Zone B"]
        },
    },

    // this is 4 zone
    "Block 18C": {
        levelOne: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
        },
        levelTwo: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "11": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "12": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "13": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "14": ["Zone A", "Zone B", "Zone C", "Zone D"],
        },
        levelThree: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "11": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "12": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "13": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "14": ["Zone A", "Zone B", "Zone C", "Zone D"],
        },
        levelFour: {
            "01": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "02": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "03": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "04": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "05": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "06": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "07": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "08": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "09": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "10": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "11": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "12": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "13": ["Zone A", "Zone B", "Zone C", "Zone D"],
            "14": ["Zone A", "Zone B", "Zone C", "Zone D"],
        },
    },

    // this is 3 zone
    "Block 18D": {
        levelOne: {
            "01": ["Zone A", "Zone B", "Zone C"],
            "02": ["Zone A", "Zone B", "Zone C"],
            "03": ["Zone A", "Zone B", "Zone C"],
            "04": ["Zone A", "Zone B", "Zone C"],
            "05": ["Zone A", "Zone B", "Zone C"],
            "06": ["Zone A", "Zone B", "Zone C"],
            "07": ["Zone A", "Zone B", "Zone C"],
            "08": ["Zone A", "Zone B", "Zone C"],
        },
        levelTwo: {
            "01": ["Zone A", "Zone B", "Zone C"],
            "02": ["Zone A", "Zone B", "Zone C"],
            "03": ["Zone A", "Zone B", "Zone C"],
            "04": ["Zone A", "Zone B", "Zone C"],
            "05": ["Zone A", "Zone B", "Zone C"],
            "06": ["Zone A", "Zone B", "Zone C"],
            "07": ["Zone A", "Zone B", "Zone C"],
            "08": ["Zone A", "Zone B", "Zone C"],
            "09": ["Zone A", "Zone B", "Zone C"],
            "10": ["Zone A", "Zone B", "Zone C"],
            "11": ["Zone A", "Zone B", "Zone C"],
            "12": ["Zone A", "Zone B", "Zone C"],
            "13": ["Zone A", "Zone B", "Zone C"],
            "14": ["Zone A", "Zone B", "Zone C"],
        },
        levelThree: {
            "01": ["Zone A", "Zone B", "Zone C"],
            "02": ["Zone A", "Zone B", "Zone C"],
            "03": ["Zone A", "Zone B", "Zone C"],
            "04": ["Zone A", "Zone B", "Zone C"],
            "05": ["Zone A", "Zone B", "Zone C"],
            "06": ["Zone A", "Zone B", "Zone C"],
            "07": ["Zone A", "Zone B", "Zone C"],
            "08": ["Zone A", "Zone B", "Zone C"],
            "09": ["Zone A", "Zone B", "Zone C"],
            "10": ["Zone A", "Zone B", "Zone C"],
            "11": ["Zone A", "Zone B", "Zone C"],
            "12": ["Zone A", "Zone B", "Zone C"],
            "13": ["Zone A", "Zone B", "Zone C"],
            "14": ["Zone A", "Zone B", "Zone C"],
        },
        levelFour: {
            "01": ["Zone A", "Zone B", "Zone C"],
            "02": ["Zone A", "Zone B", "Zone C"],
            "03": ["Zone A", "Zone B", "Zone C"],
            "04": ["Zone A", "Zone B", "Zone C"],
            "05": ["Zone A", "Zone B", "Zone C"],
            "06": ["Zone A", "Zone B", "Zone C"],
            "07": ["Zone A", "Zone B", "Zone C"],
            "08": ["Zone A", "Zone B", "Zone C"],
            "09": ["Zone A", "Zone B", "Zone C"],
            "10": ["Zone A", "Zone B", "Zone C"],
            "11": ["Zone A", "Zone B", "Zone C"],
            "12": ["Zone A", "Zone B", "Zone C"],
            "13": ["Zone A", "Zone B", "Zone C"],
            "14": ["Zone A", "Zone B", "Zone C"],
        },
    },
};
